# Generated by Django 2.0.7 on 2018-07-25 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_web2', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='person',
            new_name='person1',
        ),
    ]
