# Generated by Django 2.0.7 on 2018-07-25 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_web2', '0003_auto_20180725_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=30, null=True, verbose_name='张三'),
        ),
    ]
