# Generated by Django 2.0.7 on 2018-07-25 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_web2', '0005_auto_20180725_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='pp',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=30, null=True, verbose_name='张wu'),
        ),
    ]
